# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='poster',
            field=models.ManyToManyField(related_name='quote_poster', to='quotes.User'),
        ),
    ]
